// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/federation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FedHello is sent by both nodes simultaneously immediately after the QUIC
// handshake. Neither side waits for the other — both send and receive
// concurrently. The TLS-exporter nonce is derived under the label
// "lattice-fed-hello-v1" (distinct from the client label "lattice-hello-v1").
type FedHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pubkey          []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                                           // Ed25519 public key (32 bytes)
	Signature       []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                                     // sig over TLS-exporter nonce, label "lattice-fed-hello-v1"
	ProtocolVersion uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // must equal FedProtocolVersion = 1
	NodeName        string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                       // human-readable display name; informational only
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FedHello) Reset() {
	*x = FedHello{}
	mi := &file_proto_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedHello) ProtoMessage() {}

func (x *FedHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedHello.ProtoReflect.Descriptor instead.
func (*FedHello) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{0}
}

func (x *FedHello) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *FedHello) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *FedHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *FedHello) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

// FedHelloAck is an empty acknowledgment sent after verifying the peer's
// FedHello. Receipt confirms that both parties verified each other's identity.
type FedHelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedHelloAck) Reset() {
	*x = FedHelloAck{}
	mi := &file_proto_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedHelloAck) ProtoMessage() {}

func (x *FedHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedHelloAck.ProtoReflect.Descriptor instead.
func (*FedHelloAck) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{1}
}

// FedReject is sent when a connection is not accepted. The stream is closed
// immediately after this frame. Reasons: peer is revoked, peer is unknown
// (unsolicited), or signature/version check failed.
type FedReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedReject) Reset() {
	*x = FedReject{}
	mi := &file_proto_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedReject) ProtoMessage() {}

func (x *FedReject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedReject.ProtoReflect.Descriptor instead.
func (*FedReject) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{2}
}

func (x *FedReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// FedPending is sent to an unknown peer whose connection was accepted for
// operator review. The stream is closed after this frame. The operator must
// call POST /federation/accept before the peer can reconnect and be activated.
type FedPending struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IntroductionId string                 `protobuf:"bytes,1,opt,name=introduction_id,json=introductionId,proto3" json:"introduction_id,omitempty"` // opaque token for operator-side correlation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FedPending) Reset() {
	*x = FedPending{}
	mi := &file_proto_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedPending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedPending) ProtoMessage() {}

func (x *FedPending) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedPending.ProtoReflect.Descriptor instead.
func (*FedPending) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{3}
}

func (x *FedPending) GetIntroductionId() string {
	if x != nil {
		return x.IntroductionId
	}
	return ""
}

// FedPolicy is sent after a successful handshake on an active connection.
// It carries the forwarding policy and the list of locally-exported entity
// pubkeys (for cross-federation call routing).
type FedPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Outbound        []*FedPolicyRule       `protobuf:"bytes,1,rep,name=outbound,proto3" json:"outbound,omitempty"`                                      // subjects forwarded to the peer
	Inbound         []*FedPolicyRule       `protobuf:"bytes,2,rep,name=inbound,proto3" json:"inbound,omitempty"`                                        // subjects accepted from the peer
	ExportedPubkeys [][]byte               `protobuf:"bytes,3,rep,name=exported_pubkeys,json=exportedPubkeys,proto3" json:"exported_pubkeys,omitempty"` // Ed25519 pubkeys of exported local entities
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FedPolicy) Reset() {
	*x = FedPolicy{}
	mi := &file_proto_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedPolicy) ProtoMessage() {}

func (x *FedPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedPolicy.ProtoReflect.Descriptor instead.
func (*FedPolicy) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{4}
}

func (x *FedPolicy) GetOutbound() []*FedPolicyRule {
	if x != nil {
		return x.Outbound
	}
	return nil
}

func (x *FedPolicy) GetInbound() []*FedPolicyRule {
	if x != nil {
		return x.Inbound
	}
	return nil
}

func (x *FedPolicy) GetExportedPubkeys() [][]byte {
	if x != nil {
		return x.ExportedPubkeys
	}
	return nil
}

// FedPolicyRule is a single forwarding policy entry. Rules are evaluated in
// insertion order (first match wins). Default: deny.
type FedPolicyRule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectPattern string                 `protobuf:"bytes,1,opt,name=subject_pattern,json=subjectPattern,proto3" json:"subject_pattern,omitempty"`
	// outbound effect: "forward" | "deny"
	// inbound effect:  "accept"  | "deny"
	Effect        string `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedPolicyRule) Reset() {
	*x = FedPolicyRule{}
	mi := &file_proto_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedPolicyRule) ProtoMessage() {}

func (x *FedPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedPolicyRule.ProtoReflect.Descriptor instead.
func (*FedPolicyRule) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{5}
}

func (x *FedPolicyRule) GetSubjectPattern() string {
	if x != nil {
		return x.SubjectPattern
	}
	return ""
}

func (x *FedPolicyRule) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

// FedStatus notifies the peer of a connection state change. After sending
// FedStatus{"revoked"}, the stream is closed.
type FedStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "active" | "paused" | "revoked"
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedStatus) Reset() {
	*x = FedStatus{}
	mi := &file_proto_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedStatus) ProtoMessage() {}

func (x *FedStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedStatus.ProtoReflect.Descriptor instead.
func (*FedStatus) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{6}
}

func (x *FedStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FedStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// FedDeliver carries a forwarded Channel message across a federation boundary.
// schema_descriptor is present only on the first delivery of a given subject
// to a peer (schema propagation). Subsequent deliveries of the same subject
// omit the descriptor (schema already registered on the receiving node).
type FedDeliver struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Subject           string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Payload           []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PublisherIdentity string                 `protobuf:"bytes,3,opt,name=publisher_identity,json=publisherIdentity,proto3" json:"publisher_identity,omitempty"` // base32(origin entity pubkey), stamped by origin node
	PublishedAt       int64                  `protobuf:"varint,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`                  // Unix milliseconds
	SchemaVersion     uint32                 `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SchemaDescriptor  []byte                 `protobuf:"bytes,6,opt,name=schema_descriptor,json=schemaDescriptor,proto3" json:"schema_descriptor,omitempty"` // raw FileDescriptorProto bytes; nil after first delivery of subject
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FedDeliver) Reset() {
	*x = FedDeliver{}
	mi := &file_proto_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedDeliver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedDeliver) ProtoMessage() {}

func (x *FedDeliver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedDeliver.ProtoReflect.Descriptor instead.
func (*FedDeliver) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{7}
}

func (x *FedDeliver) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *FedDeliver) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FedDeliver) GetPublisherIdentity() string {
	if x != nil {
		return x.PublisherIdentity
	}
	return ""
}

func (x *FedDeliver) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *FedDeliver) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *FedDeliver) GetSchemaDescriptor() []byte {
	if x != nil {
		return x.SchemaDescriptor
	}
	return nil
}

// FedRequest carries a forwarded call REQUEST across a federation boundary.
// caller_identity and received_at are stamped by the origin node (not the
// requesting entity) — the receiving node can trust these fields.
type FedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId    string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TargetPubkey     []byte                 `protobuf:"bytes,2,opt,name=target_pubkey,json=targetPubkey,proto3" json:"target_pubkey,omitempty"`
	Payload          []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeoutMs        uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	CallerIdentity   string                 `protobuf:"bytes,5,opt,name=caller_identity,json=callerIdentity,proto3" json:"caller_identity,omitempty"`         // base32(requester entity pubkey), stamped by origin node
	ReceivedAt       int64                  `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`                    // Unix milliseconds, stamped by origin node
	RequesterNodePub []byte                 `protobuf:"bytes,7,opt,name=requester_node_pub,json=requesterNodePub,proto3" json:"requester_node_pub,omitempty"` // origin node's Ed25519 pubkey, for response routing
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FedRequest) Reset() {
	*x = FedRequest{}
	mi := &file_proto_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedRequest) ProtoMessage() {}

func (x *FedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedRequest.ProtoReflect.Descriptor instead.
func (*FedRequest) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{8}
}

func (x *FedRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *FedRequest) GetTargetPubkey() []byte {
	if x != nil {
		return x.TargetPubkey
	}
	return nil
}

func (x *FedRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FedRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *FedRequest) GetCallerIdentity() string {
	if x != nil {
		return x.CallerIdentity
	}
	return ""
}

func (x *FedRequest) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *FedRequest) GetRequesterNodePub() []byte {
	if x != nil {
		return x.RequesterNodePub
	}
	return nil
}

// FedResponse carries a call RESPONSE back across the federation boundary.
type FedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedResponse) Reset() {
	*x = FedResponse{}
	mi := &file_proto_federation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedResponse) ProtoMessage() {}

func (x *FedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedResponse.ProtoReflect.Descriptor instead.
func (*FedResponse) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{9}
}

func (x *FedResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *FedResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RelayRegister is sent by a node to a relay to initiate a rendezvous.
// The relay XORs local_pubkey and target_pubkey to derive a rendezvous token.
// When a second node registers with the same token (reciprocal pubkeys), the
// relay pairs the two streams and splices bytes transparently between them.
type RelayRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPubkey   []byte                 `protobuf:"bytes,1,opt,name=local_pubkey,json=localPubkey,proto3" json:"local_pubkey,omitempty"`    // Ed25519 public key of the connecting node (32 bytes)
	TargetPubkey  []byte                 `protobuf:"bytes,2,opt,name=target_pubkey,json=targetPubkey,proto3" json:"target_pubkey,omitempty"` // Ed25519 public key of the peer to rendezvous with (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRegister) Reset() {
	*x = RelayRegister{}
	mi := &file_proto_federation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRegister) ProtoMessage() {}

func (x *RelayRegister) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRegister.ProtoReflect.Descriptor instead.
func (*RelayRegister) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{10}
}

func (x *RelayRegister) GetLocalPubkey() []byte {
	if x != nil {
		return x.LocalPubkey
	}
	return nil
}

func (x *RelayRegister) GetTargetPubkey() []byte {
	if x != nil {
		return x.TargetPubkey
	}
	return nil
}

// RelayPaired is sent by the relay to both nodes once they are matched.
// After this frame, all bytes from each stream are forwarded to the other.
type RelayPaired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayPaired) Reset() {
	*x = RelayPaired{}
	mi := &file_proto_federation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayPaired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayPaired) ProtoMessage() {}

func (x *RelayPaired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayPaired.ProtoReflect.Descriptor instead.
func (*RelayPaired) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{11}
}

// RegistryRegister is sent by a node to register its current federation address.
// known_peers lists the peer pubkeys the registry should notify when this node's
// address changes. The registry matches known_peers entries to registered nodes
// and delivers push notifications to them.
type RegistryRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                           // Ed25519 public key of the registering node (32 bytes)
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                               // IPv6 addr:port of the node's federation listener
	KnownPeers    [][]byte               `protobuf:"bytes,3,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"` // pubkeys of peers to notify on address change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRegister) Reset() {
	*x = RegistryRegister{}
	mi := &file_proto_federation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRegister) ProtoMessage() {}

func (x *RegistryRegister) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRegister.ProtoReflect.Descriptor instead.
func (*RegistryRegister) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{12}
}

func (x *RegistryRegister) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *RegistryRegister) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegistryRegister) GetKnownPeers() [][]byte {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

// RegistryRegisterAck is sent by the registry to confirm a successful registration.
type RegistryRegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRegisterAck) Reset() {
	*x = RegistryRegisterAck{}
	mi := &file_proto_federation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRegisterAck) ProtoMessage() {}

func (x *RegistryRegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRegisterAck.ProtoReflect.Descriptor instead.
func (*RegistryRegisterAck) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{13}
}

// RegistryLookup is sent by a node to look up the current federation address
// of a peer by public key.
type RegistryLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // Ed25519 public key of the peer to look up (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryLookup) Reset() {
	*x = RegistryLookup{}
	mi := &file_proto_federation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryLookup) ProtoMessage() {}

func (x *RegistryLookup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryLookup.ProtoReflect.Descriptor instead.
func (*RegistryLookup) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{14}
}

func (x *RegistryLookup) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

// RegistryLookupResult is the registry's response to a RegistryLookup.
// addr is empty if the pubkey has not registered.
type RegistryLookupResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"` // current federation addr:port; empty if not found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryLookupResult) Reset() {
	*x = RegistryLookupResult{}
	mi := &file_proto_federation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryLookupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryLookupResult) ProtoMessage() {}

func (x *RegistryLookupResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryLookupResult.ProtoReflect.Descriptor instead.
func (*RegistryLookupResult) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{15}
}

func (x *RegistryLookupResult) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// RegistryNotify is pushed by the registry to a node's federation listener
// when one of its known_peers re-registers with a new address. This allows the
// node to update its stored address without polling.
type RegistryNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // Ed25519 public key of the peer whose address changed
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`     // new federation addr:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryNotify) Reset() {
	*x = RegistryNotify{}
	mi := &file_proto_federation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryNotify) ProtoMessage() {}

func (x *RegistryNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryNotify.ProtoReflect.Descriptor instead.
func (*RegistryNotify) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{16}
}

func (x *RegistryNotify) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *RegistryNotify) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_proto_federation_proto protoreflect.FileDescriptor

const file_proto_federation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/federation.proto\x12\alattice\"\x88\x01\n" +
	"\bFedHello\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\"\r\n" +
	"\vFedHelloAck\"#\n" +
	"\tFedReject\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"5\n" +
	"\n" +
	"FedPending\x12'\n" +
	"\x0fintroduction_id\x18\x01 \x01(\tR\x0eintroductionId\"\x9c\x01\n" +
	"\tFedPolicy\x122\n" +
	"\boutbound\x18\x01 \x03(\v2\x16.lattice.FedPolicyRuleR\boutbound\x120\n" +
	"\ainbound\x18\x02 \x03(\v2\x16.lattice.FedPolicyRuleR\ainbound\x12)\n" +
	"\x10exported_pubkeys\x18\x03 \x03(\fR\x0fexportedPubkeys\"P\n" +
	"\rFedPolicyRule\x12'\n" +
	"\x0fsubject_pattern\x18\x01 \x01(\tR\x0esubjectPattern\x12\x16\n" +
	"\x06effect\x18\x02 \x01(\tR\x06effect\"9\n" +
	"\tFedStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xe6\x01\n" +
	"\n" +
	"FedDeliver\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12-\n" +
	"\x12publisher_identity\x18\x03 \x01(\tR\x11publisherIdentity\x12!\n" +
	"\fpublished_at\x18\x04 \x01(\x03R\vpublishedAt\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\rR\rschemaVersion\x12+\n" +
	"\x11schema_descriptor\x18\x06 \x01(\fR\x10schemaDescriptor\"\x89\x02\n" +
	"\n" +
	"FedRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12#\n" +
	"\rtarget_pubkey\x18\x02 \x01(\fR\ftargetPubkey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\x12'\n" +
	"\x0fcaller_identity\x18\x05 \x01(\tR\x0ecallerIdentity\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAt\x12,\n" +
	"\x12requester_node_pub\x18\a \x01(\fR\x10requesterNodePub\"N\n" +
	"\vFedResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"W\n" +
	"\rRelayRegister\x12!\n" +
	"\flocal_pubkey\x18\x01 \x01(\fR\vlocalPubkey\x12#\n" +
	"\rtarget_pubkey\x18\x02 \x01(\fR\ftargetPubkey\"\r\n" +
	"\vRelayPaired\"_\n" +
	"\x10RegistryRegister\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1f\n" +
	"\vknown_peers\x18\x03 \x03(\fR\n" +
	"knownPeers\"\x15\n" +
	"\x13RegistryRegisterAck\"(\n" +
	"\x0eRegistryLookup\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\"*\n" +
	"\x14RegistryLookupResult\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"<\n" +
	"\x0eRegistryNotify\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addrB\x0fZ\rlattice/protob\x06proto3"

var (
	file_proto_federation_proto_rawDescOnce sync.Once
	file_proto_federation_proto_rawDescData []byte
)

func file_proto_federation_proto_rawDescGZIP() []byte {
	file_proto_federation_proto_rawDescOnce.Do(func() {
		file_proto_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)))
	})
	return file_proto_federation_proto_rawDescData
}

var file_proto_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_federation_proto_goTypes = []any{
	(*FedHello)(nil),             // 0: lattice.FedHello
	(*FedHelloAck)(nil),          // 1: lattice.FedHelloAck
	(*FedReject)(nil),            // 2: lattice.FedReject
	(*FedPending)(nil),           // 3: lattice.FedPending
	(*FedPolicy)(nil),            // 4: lattice.FedPolicy
	(*FedPolicyRule)(nil),        // 5: lattice.FedPolicyRule
	(*FedStatus)(nil),            // 6: lattice.FedStatus
	(*FedDeliver)(nil),           // 7: lattice.FedDeliver
	(*FedRequest)(nil),           // 8: lattice.FedRequest
	(*FedResponse)(nil),          // 9: lattice.FedResponse
	(*RelayRegister)(nil),        // 10: lattice.RelayRegister
	(*RelayPaired)(nil),          // 11: lattice.RelayPaired
	(*RegistryRegister)(nil),     // 12: lattice.RegistryRegister
	(*RegistryRegisterAck)(nil),  // 13: lattice.RegistryRegisterAck
	(*RegistryLookup)(nil),       // 14: lattice.RegistryLookup
	(*RegistryLookupResult)(nil), // 15: lattice.RegistryLookupResult
	(*RegistryNotify)(nil),       // 16: lattice.RegistryNotify
}
var file_proto_federation_proto_depIdxs = []int32{
	5, // 0: lattice.FedPolicy.outbound:type_name -> lattice.FedPolicyRule
	5, // 1: lattice.FedPolicy.inbound:type_name -> lattice.FedPolicyRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_federation_proto_init() }
func file_proto_federation_proto_init() {
	if File_proto_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_federation_proto_goTypes,
		DependencyIndexes: file_proto_federation_proto_depIdxs,
		MessageInfos:      file_proto_federation_proto_msgTypes,
	}.Build()
	File_proto_federation_proto = out.File
	file_proto_federation_proto_goTypes = nil
	file_proto_federation_proto_depIdxs = nil
}
