// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/frames.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── Frame type enum ────────────────────────────────────────────────────────
// Values 0–14: client↔server frames (TLS-over-TCP connections).
// Values 15–23: federation frames (QUIC peer connections only; never on client connections).
type FrameType int32

const (
	FrameType_FRAME_TYPE_UNKNOWN       FrameType = 0
	FrameType_FRAME_TYPE_HELLO         FrameType = 1
	FrameType_FRAME_TYPE_HELLO_ACK     FrameType = 2
	FrameType_FRAME_TYPE_HEARTBEAT     FrameType = 3
	FrameType_FRAME_TYPE_HEARTBEAT_ACK FrameType = 4
	FrameType_FRAME_TYPE_SUBSCRIBE     FrameType = 5
	FrameType_FRAME_TYPE_UNSUBSCRIBE   FrameType = 6
	FrameType_FRAME_TYPE_PUBLISH       FrameType = 7
	FrameType_FRAME_TYPE_DELIVER       FrameType = 8
	FrameType_FRAME_TYPE_ERROR         FrameType = 9
	FrameType_FRAME_TYPE_REQUEST       FrameType = 10
	FrameType_FRAME_TYPE_RESPONSE      FrameType = 11
	FrameType_FRAME_TYPE_DISCONNECT    FrameType = 12
	FrameType_FRAME_TYPE_PING          FrameType = 13 // Reserved — no handler; do not build client code against this
	FrameType_FRAME_TYPE_PONG          FrameType = 14 // Reserved — no handler; do not build client code against this
	// Federation frames — QUIC peer connections only (v0.2+)
	FrameType_FRAME_TYPE_FED_HELLO     FrameType = 15
	FrameType_FRAME_TYPE_FED_HELLO_ACK FrameType = 16
	FrameType_FRAME_TYPE_FED_REJECT    FrameType = 17
	FrameType_FRAME_TYPE_FED_PENDING   FrameType = 18
	FrameType_FRAME_TYPE_FED_POLICY    FrameType = 19
	FrameType_FRAME_TYPE_FED_STATUS    FrameType = 20
	FrameType_FRAME_TYPE_FED_DELIVER   FrameType = 21
	FrameType_FRAME_TYPE_FED_REQUEST   FrameType = 22
	FrameType_FRAME_TYPE_FED_RESPONSE  FrameType = 23
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0:  "FRAME_TYPE_UNKNOWN",
		1:  "FRAME_TYPE_HELLO",
		2:  "FRAME_TYPE_HELLO_ACK",
		3:  "FRAME_TYPE_HEARTBEAT",
		4:  "FRAME_TYPE_HEARTBEAT_ACK",
		5:  "FRAME_TYPE_SUBSCRIBE",
		6:  "FRAME_TYPE_UNSUBSCRIBE",
		7:  "FRAME_TYPE_PUBLISH",
		8:  "FRAME_TYPE_DELIVER",
		9:  "FRAME_TYPE_ERROR",
		10: "FRAME_TYPE_REQUEST",
		11: "FRAME_TYPE_RESPONSE",
		12: "FRAME_TYPE_DISCONNECT",
		13: "FRAME_TYPE_PING",
		14: "FRAME_TYPE_PONG",
		15: "FRAME_TYPE_FED_HELLO",
		16: "FRAME_TYPE_FED_HELLO_ACK",
		17: "FRAME_TYPE_FED_REJECT",
		18: "FRAME_TYPE_FED_PENDING",
		19: "FRAME_TYPE_FED_POLICY",
		20: "FRAME_TYPE_FED_STATUS",
		21: "FRAME_TYPE_FED_DELIVER",
		22: "FRAME_TYPE_FED_REQUEST",
		23: "FRAME_TYPE_FED_RESPONSE",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNKNOWN":       0,
		"FRAME_TYPE_HELLO":         1,
		"FRAME_TYPE_HELLO_ACK":     2,
		"FRAME_TYPE_HEARTBEAT":     3,
		"FRAME_TYPE_HEARTBEAT_ACK": 4,
		"FRAME_TYPE_SUBSCRIBE":     5,
		"FRAME_TYPE_UNSUBSCRIBE":   6,
		"FRAME_TYPE_PUBLISH":       7,
		"FRAME_TYPE_DELIVER":       8,
		"FRAME_TYPE_ERROR":         9,
		"FRAME_TYPE_REQUEST":       10,
		"FRAME_TYPE_RESPONSE":      11,
		"FRAME_TYPE_DISCONNECT":    12,
		"FRAME_TYPE_PING":          13,
		"FRAME_TYPE_PONG":          14,
		"FRAME_TYPE_FED_HELLO":     15,
		"FRAME_TYPE_FED_HELLO_ACK": 16,
		"FRAME_TYPE_FED_REJECT":    17,
		"FRAME_TYPE_FED_PENDING":   18,
		"FRAME_TYPE_FED_POLICY":    19,
		"FRAME_TYPE_FED_STATUS":    20,
		"FRAME_TYPE_FED_DELIVER":   21,
		"FRAME_TYPE_FED_REQUEST":   22,
		"FRAME_TYPE_FED_RESPONSE":  23,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_frames_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_proto_frames_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{0}
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // capability identifier e.g. "sensor", "actuator"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_proto_frames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pubkey          []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`       // Ed25519 public key (32 bytes)
	Signature       []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature over client TLS-exporter nonce (64 bytes)
	Capabilities    []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // must equal ProtocolVersion=1; server rejects mismatches
	ResumeToken     []byte                 `protobuf:"bytes,5,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`              // optional; 32-byte token from a prior HELLO_ACK (Decision #2)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_frames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Hello) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Hello) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetResumeToken() []byte {
	if x != nil {
		return x.ResumeToken
	}
	return nil
}

type HelloAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken      []byte                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`                 // 32 random bytes
	ServerPubkey      []byte                 `protobuf:"bytes,3,opt,name=server_pubkey,json=serverPubkey,proto3" json:"server_pubkey,omitempty"`                 // Ed25519 public key (32 bytes)
	HeartbeatInterval uint32                 `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // seconds
	ServerSignature   []byte                 `protobuf:"bytes,5,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`        // Ed25519 signature over server TLS-exporter nonce (64 bytes)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_proto_frames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HelloAck) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *HelloAck) GetServerPubkey() []byte {
	if x != nil {
		return x.ServerPubkey
	}
	return nil
}

func (x *HelloAck) GetHeartbeatInterval() uint32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *HelloAck) GetServerSignature() []byte {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_frames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{3}
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_frames_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{4}
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_proto_frames_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{5}
}

func (x *Subscribe) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_proto_frames_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{6}
}

func (x *Unsubscribe) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type Publish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // client-assigned; echoed in Error.ref_id on failure (Decision #5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_proto_frames_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{7}
}

func (x *Publish) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Publish) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Publish) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type Deliver struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Subject           string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Payload           []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Id                uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`                                                       // per-subject monotonic counter, server-assigned (Decision #4)
	PublisherIdentity string                 `protobuf:"bytes,4,opt,name=publisher_identity,json=publisherIdentity,proto3" json:"publisher_identity,omitempty"` // base32 pubkey of publisher, server-stamped (Decision #4)
	PublishedAt       int64                  `protobuf:"varint,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`                  // Unix milliseconds, server timestamp (Decision #4)
	SchemaVersion     uint32                 `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`            // from schema registry; 0 if no registered schema (Decision #4)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Deliver) Reset() {
	*x = Deliver{}
	mi := &file_proto_frames_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deliver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deliver) ProtoMessage() {}

func (x *Deliver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deliver.ProtoReflect.Descriptor instead.
func (*Deliver) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{8}
}

func (x *Deliver) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Deliver) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Deliver) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Deliver) GetPublisherIdentity() string {
	if x != nil {
		return x.PublisherIdentity
	}
	return ""
}

func (x *Deliver) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *Deliver) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TargetPubkey   []byte                 `protobuf:"bytes,2,opt,name=target_pubkey,json=targetPubkey,proto3" json:"target_pubkey,omitempty"` // Ed25519 public key of target entity (32 bytes)
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeoutMs      uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	CallerIdentity string                 `protobuf:"bytes,5,opt,name=caller_identity,json=callerIdentity,proto3" json:"caller_identity,omitempty"` // base32 pubkey of requester, server-stamped; client-supplied value is overwritten (Decision #18)
	ReceivedAt     int64                  `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`            // Unix milliseconds, server timestamp (Decision #18)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_frames_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{9}
}

func (x *Request) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Request) GetTargetPubkey() []byte {
	if x != nil {
		return x.TargetPubkey
	}
	return nil
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Request) GetCallerIdentity() string {
	if x != nil {
		return x.CallerIdentity
	}
	return ""
}

func (x *Request) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_frames_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RefId         string                 `protobuf:"bytes,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"` // echoes Publish.message_id on publish errors, or correlation_id on call timeout (Decision #5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_frames_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_proto_frames_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{12}
}

func (x *Disconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_frames_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{13}
}

func (x *Ping) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_frames_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frames_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_frames_proto_rawDescGZIP(), []int{14}
}

func (x *Pong) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_proto_frames_proto protoreflect.FileDescriptor

const file_proto_frames_proto_rawDesc = "" +
	"\n" +
	"\x12proto/frames.proto\x12\alattice\" \n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc4\x01\n" +
	"\x05Hello\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x127\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x13.lattice.CapabilityR\fcapabilities\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\x12!\n" +
	"\fresume_token\x18\x05 \x01(\fR\vresumeToken\"\xcd\x01\n" +
	"\bHelloAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\fR\fsessionToken\x12#\n" +
	"\rserver_pubkey\x18\x03 \x01(\fR\fserverPubkey\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\rR\x11heartbeatInterval\x12)\n" +
	"\x10server_signature\x18\x05 \x01(\fR\x0fserverSignature\"\v\n" +
	"\tHeartbeat\"\x0e\n" +
	"\fHeartbeatAck\"%\n" +
	"\tSubscribe\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"'\n" +
	"\vUnsubscribe\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"\\\n" +
	"\aPublish\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\xc6\x01\n" +
	"\aDeliver\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\x12-\n" +
	"\x12publisher_identity\x18\x04 \x01(\tR\x11publisherIdentity\x12!\n" +
	"\fpublished_at\x18\x05 \x01(\x03R\vpublishedAt\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\rR\rschemaVersion\"\xd8\x01\n" +
	"\aRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12#\n" +
	"\rtarget_pubkey\x18\x02 \x01(\fR\ftargetPubkey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\x12'\n" +
	"\x0fcaller_identity\x18\x05 \x01(\tR\x0ecallerIdentity\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAt\"K\n" +
	"\bResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"L\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06ref_id\x18\x03 \x01(\tR\x05refId\"$\n" +
	"\n" +
	"Disconnect\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce*\xf7\x04\n" +
	"\tFrameType\x12\x16\n" +
	"\x12FRAME_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10FRAME_TYPE_HELLO\x10\x01\x12\x18\n" +
	"\x14FRAME_TYPE_HELLO_ACK\x10\x02\x12\x18\n" +
	"\x14FRAME_TYPE_HEARTBEAT\x10\x03\x12\x1c\n" +
	"\x18FRAME_TYPE_HEARTBEAT_ACK\x10\x04\x12\x18\n" +
	"\x14FRAME_TYPE_SUBSCRIBE\x10\x05\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSUBSCRIBE\x10\x06\x12\x16\n" +
	"\x12FRAME_TYPE_PUBLISH\x10\a\x12\x16\n" +
	"\x12FRAME_TYPE_DELIVER\x10\b\x12\x14\n" +
	"\x10FRAME_TYPE_ERROR\x10\t\x12\x16\n" +
	"\x12FRAME_TYPE_REQUEST\x10\n" +
	"\x12\x17\n" +
	"\x13FRAME_TYPE_RESPONSE\x10\v\x12\x19\n" +
	"\x15FRAME_TYPE_DISCONNECT\x10\f\x12\x13\n" +
	"\x0fFRAME_TYPE_PING\x10\r\x12\x13\n" +
	"\x0fFRAME_TYPE_PONG\x10\x0e\x12\x18\n" +
	"\x14FRAME_TYPE_FED_HELLO\x10\x0f\x12\x1c\n" +
	"\x18FRAME_TYPE_FED_HELLO_ACK\x10\x10\x12\x19\n" +
	"\x15FRAME_TYPE_FED_REJECT\x10\x11\x12\x1a\n" +
	"\x16FRAME_TYPE_FED_PENDING\x10\x12\x12\x19\n" +
	"\x15FRAME_TYPE_FED_POLICY\x10\x13\x12\x19\n" +
	"\x15FRAME_TYPE_FED_STATUS\x10\x14\x12\x1a\n" +
	"\x16FRAME_TYPE_FED_DELIVER\x10\x15\x12\x1a\n" +
	"\x16FRAME_TYPE_FED_REQUEST\x10\x16\x12\x1b\n" +
	"\x17FRAME_TYPE_FED_RESPONSE\x10\x17B\x0fZ\rlattice/protob\x06proto3"

var (
	file_proto_frames_proto_rawDescOnce sync.Once
	file_proto_frames_proto_rawDescData []byte
)

func file_proto_frames_proto_rawDescGZIP() []byte {
	file_proto_frames_proto_rawDescOnce.Do(func() {
		file_proto_frames_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_frames_proto_rawDesc), len(file_proto_frames_proto_rawDesc)))
	})
	return file_proto_frames_proto_rawDescData
}

var file_proto_frames_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_frames_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_frames_proto_goTypes = []any{
	(FrameType)(0),       // 0: lattice.FrameType
	(*Capability)(nil),   // 1: lattice.Capability
	(*Hello)(nil),        // 2: lattice.Hello
	(*HelloAck)(nil),     // 3: lattice.HelloAck
	(*Heartbeat)(nil),    // 4: lattice.Heartbeat
	(*HeartbeatAck)(nil), // 5: lattice.HeartbeatAck
	(*Subscribe)(nil),    // 6: lattice.Subscribe
	(*Unsubscribe)(nil),  // 7: lattice.Unsubscribe
	(*Publish)(nil),      // 8: lattice.Publish
	(*Deliver)(nil),      // 9: lattice.Deliver
	(*Request)(nil),      // 10: lattice.Request
	(*Response)(nil),     // 11: lattice.Response
	(*Error)(nil),        // 12: lattice.Error
	(*Disconnect)(nil),   // 13: lattice.Disconnect
	(*Ping)(nil),         // 14: lattice.Ping
	(*Pong)(nil),         // 15: lattice.Pong
}
var file_proto_frames_proto_depIdxs = []int32{
	1, // 0: lattice.Hello.capabilities:type_name -> lattice.Capability
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_frames_proto_init() }
func file_proto_frames_proto_init() {
	if File_proto_frames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_frames_proto_rawDesc), len(file_proto_frames_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_frames_proto_goTypes,
		DependencyIndexes: file_proto_frames_proto_depIdxs,
		EnumInfos:         file_proto_frames_proto_enumTypes,
		MessageInfos:      file_proto_frames_proto_msgTypes,
	}.Build()
	File_proto_frames_proto = out.File
	file_proto_frames_proto_goTypes = nil
	file_proto_frames_proto_depIdxs = nil
}
