// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/lattice_options.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RangeOptions constrains the numeric or enum value of a field.
type RangeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float32                `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeOptions) Reset() {
	*x = RangeOptions{}
	mi := &file_proto_lattice_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeOptions) ProtoMessage() {}

func (x *RangeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lattice_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeOptions.ProtoReflect.Descriptor instead.
func (*RangeOptions) Descriptor() ([]byte, []int) {
	return file_proto_lattice_options_proto_rawDescGZIP(), []int{0}
}

func (x *RangeOptions) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *RangeOptions) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

var file_proto_lattice_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*RangeOptions)(nil),
		Field:         50001,
		Name:          "lattice.range",
		Tag:           "bytes,50001,opt,name=range",
		Filename:      "proto/lattice_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50002,
		Name:          "lattice.max_length",
		Tag:           "varint,50002,opt,name=max_length",
		Filename:      "proto/lattice_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "lattice.required",
		Tag:           "varint,50003,opt,name=required",
		Filename:      "proto/lattice_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// lattice.range constrains the min/max value of a numeric or enum field.
	//
	// optional lattice.RangeOptions range = 50001;
	E_Range = &file_proto_lattice_options_proto_extTypes[0]
	// lattice.max_length constrains the maximum byte length of a string field.
	//
	// optional uint32 max_length = 50002;
	E_MaxLength = &file_proto_lattice_options_proto_extTypes[1]
	// lattice.required marks a field as required (must be present).
	//
	// optional bool required = 50003;
	E_Required = &file_proto_lattice_options_proto_extTypes[2]
)

var File_proto_lattice_options_proto protoreflect.FileDescriptor

const file_proto_lattice_options_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/lattice_options.proto\x12\alattice\x1a google/protobuf/descriptor.proto\"2\n" +
	"\fRangeOptions\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x02R\x03max:L\n" +
	"\x05range\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x15.lattice.RangeOptionsR\x05range:>\n" +
	"\n" +
	"max_length\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\rR\tmaxLength:;\n" +
	"\brequired\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\bR\brequiredB\x0fZ\rlattice/protob\x06proto3"

var (
	file_proto_lattice_options_proto_rawDescOnce sync.Once
	file_proto_lattice_options_proto_rawDescData []byte
)

func file_proto_lattice_options_proto_rawDescGZIP() []byte {
	file_proto_lattice_options_proto_rawDescOnce.Do(func() {
		file_proto_lattice_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lattice_options_proto_rawDesc), len(file_proto_lattice_options_proto_rawDesc)))
	})
	return file_proto_lattice_options_proto_rawDescData
}

var file_proto_lattice_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_lattice_options_proto_goTypes = []any{
	(*RangeOptions)(nil),              // 0: lattice.RangeOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_proto_lattice_options_proto_depIdxs = []int32{
	1, // 0: lattice.range:extendee -> google.protobuf.FieldOptions
	1, // 1: lattice.max_length:extendee -> google.protobuf.FieldOptions
	1, // 2: lattice.required:extendee -> google.protobuf.FieldOptions
	0, // 3: lattice.range:type_name -> lattice.RangeOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lattice_options_proto_init() }
func file_proto_lattice_options_proto_init() {
	if File_proto_lattice_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lattice_options_proto_rawDesc), len(file_proto_lattice_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_proto_lattice_options_proto_goTypes,
		DependencyIndexes: file_proto_lattice_options_proto_depIdxs,
		MessageInfos:      file_proto_lattice_options_proto_msgTypes,
		ExtensionInfos:    file_proto_lattice_options_proto_extTypes,
	}.Build()
	File_proto_lattice_options_proto = out.File
	file_proto_lattice_options_proto_goTypes = nil
	file_proto_lattice_options_proto_depIdxs = nil
}
