// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/schemas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LightAction is the valid command set for home.light.command.
type LightAction int32

const (
	LightAction_LIGHT_ACTION_UNSPECIFIED LightAction = 0
	LightAction_LIGHT_ACTION_ON          LightAction = 1
	LightAction_LIGHT_ACTION_OFF         LightAction = 2
	LightAction_LIGHT_ACTION_TOGGLE      LightAction = 3
)

// Enum value maps for LightAction.
var (
	LightAction_name = map[int32]string{
		0: "LIGHT_ACTION_UNSPECIFIED",
		1: "LIGHT_ACTION_ON",
		2: "LIGHT_ACTION_OFF",
		3: "LIGHT_ACTION_TOGGLE",
	}
	LightAction_value = map[string]int32{
		"LIGHT_ACTION_UNSPECIFIED": 0,
		"LIGHT_ACTION_ON":          1,
		"LIGHT_ACTION_OFF":         2,
		"LIGHT_ACTION_TOGGLE":      3,
	}
)

func (x LightAction) Enum() *LightAction {
	p := new(LightAction)
	*p = x
	return p
}

func (x LightAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LightAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schemas_proto_enumTypes[0].Descriptor()
}

func (LightAction) Type() protoreflect.EnumType {
	return &file_proto_schemas_proto_enumTypes[0]
}

func (x LightAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LightAction.Descriptor instead.
func (LightAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_schemas_proto_rawDescGZIP(), []int{0}
}

// TemperatureReading is published to home.sensor.temperature.
// value is required; range -50.0 .. 150.0 °C.
// unit is optional; max 10 chars.
type TemperatureReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float32               `protobuf:"fixed32,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Unit          *string                `protobuf:"bytes,2,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureReading) Reset() {
	*x = TemperatureReading{}
	mi := &file_proto_schemas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureReading) ProtoMessage() {}

func (x *TemperatureReading) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schemas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureReading.ProtoReflect.Descriptor instead.
func (*TemperatureReading) Descriptor() ([]byte, []int) {
	return file_proto_schemas_proto_rawDescGZIP(), []int{0}
}

func (x *TemperatureReading) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *TemperatureReading) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

// LightCommand is published to home.light.command.
// action is required (ON/OFF/TOGGLE, range 1..3); brightness is optional (0.0..1.0).
type LightCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *LightAction           `protobuf:"varint,1,opt,name=action,proto3,enum=lattice.LightAction,oneof" json:"action,omitempty"`
	Brightness    *float32               `protobuf:"fixed32,2,opt,name=brightness,proto3,oneof" json:"brightness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightCommand) Reset() {
	*x = LightCommand{}
	mi := &file_proto_schemas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightCommand) ProtoMessage() {}

func (x *LightCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schemas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightCommand.ProtoReflect.Descriptor instead.
func (*LightCommand) Descriptor() ([]byte, []int) {
	return file_proto_schemas_proto_rawDescGZIP(), []int{1}
}

func (x *LightCommand) GetAction() LightAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return LightAction_LIGHT_ACTION_UNSPECIFIED
}

func (x *LightCommand) GetBrightness() float32 {
	if x != nil && x.Brightness != nil {
		return *x.Brightness
	}
	return 0
}

var File_proto_schemas_proto protoreflect.FileDescriptor

const file_proto_schemas_proto_rawDesc = "" +
	"\n" +
	"\x13proto/schemas.proto\x12\alattice\x1a\x1bproto/lattice_options.proto\"u\n" +
	"\x12TemperatureReading\x12-\n" +
	"\x05value\x18\x01 \x01(\x02B\x12\x8a\xb5\x18\n" +
	"\r\x00\x00H\xc2\x15\x00\x00\x16C\x98\xb5\x18\x01H\x00R\x05value\x88\x01\x01\x12\x1d\n" +
	"\x04unit\x18\x02 \x01(\tB\x04\x90\xb5\x18\n" +
	"H\x01R\x04unit\x88\x01\x01B\b\n" +
	"\x06_valueB\a\n" +
	"\x05_unit\"\x9f\x01\n" +
	"\fLightCommand\x12E\n" +
	"\x06action\x18\x01 \x01(\x0e2\x14.lattice.LightActionB\x12\x8a\xb5\x18\n" +
	"\r\x00\x00\x80?\x15\x00\x00@@\x98\xb5\x18\x01H\x00R\x06action\x88\x01\x01\x12.\n" +
	"\n" +
	"brightness\x18\x02 \x01(\x02B\t\x8a\xb5\x18\x05\x15\x00\x00\x80?H\x01R\n" +
	"brightness\x88\x01\x01B\t\n" +
	"\a_actionB\r\n" +
	"\v_brightness*o\n" +
	"\vLightAction\x12\x1c\n" +
	"\x18LIGHT_ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLIGHT_ACTION_ON\x10\x01\x12\x14\n" +
	"\x10LIGHT_ACTION_OFF\x10\x02\x12\x17\n" +
	"\x13LIGHT_ACTION_TOGGLE\x10\x03B\x0fZ\rlattice/protob\x06proto3"

var (
	file_proto_schemas_proto_rawDescOnce sync.Once
	file_proto_schemas_proto_rawDescData []byte
)

func file_proto_schemas_proto_rawDescGZIP() []byte {
	file_proto_schemas_proto_rawDescOnce.Do(func() {
		file_proto_schemas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schemas_proto_rawDesc), len(file_proto_schemas_proto_rawDesc)))
	})
	return file_proto_schemas_proto_rawDescData
}

var file_proto_schemas_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_schemas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_schemas_proto_goTypes = []any{
	(LightAction)(0),           // 0: lattice.LightAction
	(*TemperatureReading)(nil), // 1: lattice.TemperatureReading
	(*LightCommand)(nil),       // 2: lattice.LightCommand
}
var file_proto_schemas_proto_depIdxs = []int32{
	0, // 0: lattice.LightCommand.action:type_name -> lattice.LightAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_schemas_proto_init() }
func file_proto_schemas_proto_init() {
	if File_proto_schemas_proto != nil {
		return
	}
	file_proto_lattice_options_proto_init()
	file_proto_schemas_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_schemas_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schemas_proto_rawDesc), len(file_proto_schemas_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_schemas_proto_goTypes,
		DependencyIndexes: file_proto_schemas_proto_depIdxs,
		EnumInfos:         file_proto_schemas_proto_enumTypes,
		MessageInfos:      file_proto_schemas_proto_msgTypes,
	}.Build()
	File_proto_schemas_proto = out.File
	file_proto_schemas_proto_goTypes = nil
	file_proto_schemas_proto_depIdxs = nil
}
